services:
  mariadb:
    platform: linux/arm64
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mpp
    networks:
        - spring1
    volumes:
      - mysqlvol:/var/lib/mysql
  app:
    platform: linux/arm64
    image: bog1200/mpp_server
    ports:
      - 6777:8080
    build: .
    networks:
      - spring1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/mpp
    depends_on:
      - mariadb
volumes:
  mysqlvol: {}
networks:
  spring1: {}
